--Primera versión del schema

CREATE TABLE IF NOT EXISTS groups (
  groupid INTEGER PRIMARY KEY ON CONFLICT ABORT
);

CREATE TABLE IF NOT EXISTS users (
  userid INTEGER PRIMARY KEY ON CONFLICT ABORT
);

CREATE TABLE IF NOT EXISTS group_users (
  groupid INTEGER REFERENCES groups(groupid) ON DELETE CASCADE ON UPDATE CASCADE,
  userid INTEGER REFERENCES users(userid) ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY (groupid, userid) ON CONFLICT IGNORE
);

CREATE TABLE IF NOT EXISTS group_preferences (
  groupid INTEGER REFERENCES groups(groupid) ON DELETE CASCADE ON UPDATE CASCADE,
  pref TEXT NOT NULL,
  value TEXT,
  PRIMARY KEY (groupid, pref) ON CONFLICT ABORT
);

CREATE TABLE IF NOT EXISTS parts (
  id INTEGER PRIMARY KEY ON CONFLICT ABORT AUTOINCREMENT,
  a TEXT,
  b TEXT,
  c TEXT,
  isstart BOOL NOT NULL,
  isend BOOL NOT NULL,
  groupid INTEGER NOT NULL REFERENCES groups(groupid) ON DELETE CASCADE ON UPDATE CASCADE,
  userid INTEGER REFERENCES users(userid) ON DELETE SET NULL ON UPDATE CASCADE DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS database (
  property TEXT PRIMARY KEY,
  value TEXT
);

INSERT OR IGNORE INTO database VALUES ('database.version', '0');